#!/bin/bash
set -e
export YODA_HOST=${YODA_HOST:="127.0.0.1"}
export YODA_PORT=${YODA_PORT:=4001}
case "$1" in

  set)
    YODA_PATH="$2";
    YODA_DATA="$3";
    if [[ -z $YODA_PATH || -z $YODA_DATA ]]; then
        echo "usage: yoda set <path> <data>";
        exit 1;
    fi
    YODA_PATH=`echo $YODA_PATH | sed -r 's/^\///'`
    curl -L http://$YODA_HOST:$YODA_PORT/v2/keys/$YODA_PATH -X PUT -d value="$YODA_DATA"
    ;;

  get)
    YODA_PATH="$2";
    if [[ -z $YODA_PATH ]]; then
        echo "usage: yoda get <path>";
        exit 1;
    fi
    YODA_PATH=`echo $YODA_PATH | sed -r 's/^\///'`
    curl -L http://$YODA_HOST:$YODA_PORT/v2/keys/$YODA_PATH
    ;;

  del)
    YODA_PATH="$2";
    if [[ -z $YODA_PATH ]]; then
        echo "usage: yoda del <path>";
        exit 1;
    fi
    YODA_PATH=`echo $YODA_PATH | sed -r 's/^\///'`
    curl -L http://$YODA_HOST:$YODA_PORT/v2/keys/$YODA_PATH -X DELETE > /dev/null 2>&1
    ;;

  rmdir)
    YODA_PATH="$2";
    if [[ -z $YODA_PATH ]]; then
        echo "usage: yoda rmdir <path>";
        exit 1;
    fi
    curl -L -X DELETE "http://$YODA_HOST:$YODA_PORT/v2/keys/$YODA_PATH?recursive=true"
    ;;

  help)
    cat<<EOF

    get <path>            Read the value of path
    set <path> <data>     Write the value of path
    del <path>            Remove path
    help                  Print the list of commands

EOF
    ;;

  *)
    echo "usage: yoda command [options]"
    yoda help
    exit 1
    ;;

esac
