#!/bin/bash
set -e
export YODA_HOST=${YODA_HOST:="127.0.0.1"}
export YODA_PORT=${QUARRY_HOME:=4001}
case "$1" in
  get)
    YODA_PATH="$2";
    YODA_PATH=`echo $YODA_PATH | sed -r 's/^\///'`
    curl -L http://$YODA_HOST:$YODA_PORT/v1/keys/$YODA_PATH
    ;;

  set)
    YODA_PATH="$2";
    YODA_DATA="$3";
    YODA_PATH=`echo $YODA_PATH | sed -r 's/^\///'`
    curl -L http://$YODA_HOST:$YODA_PORT/v1/keys/$YODA_PATH -d value=$YODA_DATA > /dev/null 2>&1
    ;;

  del)
    YODA_PATH="$2";
    YODA_PATH=`echo $YODA_PATH | sed -r 's/^\///'`
    curl -L http://$YODA_HOST:$YODA_PORT/v1/keys/$YODA_PATH -X DELETE > /dev/null 2>&1
    ;;

  help)
    cat<<EOF | sort
    help                  Print the list of commands
    add <path> <data>     Add a node to path
    remove <path>         Remove a path
EOF
    ;;

  *)
    yoda help
    ;;

esac
